---
title: "correlation with wbgt"
output: html_document
date: "2026-02-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ncdf4)
library(terra)
library(parallel)
```

```{r}
# open wbgt_aug_2019.nc
wbgt_aug_2019 <- nc_open("wbgt_aug_2019.nc")
names(wbgt_aug_2019$var)
dim(ncvar_get(wbgt_aug_2019, "wbgt")) # R shows dimensions as longitude x latitude x time
```

```{r}
# open wbgt_inputs_aug_2019.nc
wbgt_inputs_aug_2019 <- nc_open("wbgt_inputs_aug_2019.nc")
names(wbgt_inputs_aug_2019$var)
dim(ncvar_get(wbgt_inputs_aug_2019, "Tair")) # R shows dimensions as longitude x latitude x time
```

```{r}
times <- as.POSIXct(ncvar_get(wbgt_aug_2019, "valid_time"), origin = "1970-01-01", tz = "UTC")
t_index <- which(times == as.POSIXct("2019-08-01 18:00", tz="UTC"))

# plot with wet-bulb globe temp at a single valid_time
r <- rast("wbgt_aug_2019.nc", subds = "wbgt")
plot(r[[t_index]])
title(main = paste("wbgt at", times[t_index]), line=3)

# plot dry-bulb air temperature at a single valid_time
r <- rast("wbgt_inputs_aug_2019.nc", subds = "Tair")
plot(r[[t_index]])
title(main = paste("dry-bulb air temp at", times[t_index]), line=3)
```

```{r}
# overall correlation

wbgt <- ncvar_get(wbgt_aug_2019, "wbgt")
atemp <- ncvar_get(wbgt_inputs_aug_2019, "Tair")

cor(as.vector(wbgt), as.vector(atemp), use = "complete.obs")
```

```{r}
# spatial correlation at each hour

nlon  <- dim(atemp)[1]  # 105
nlat  <- dim(atemp)[2]  # 96
ntime <- dim(atemp)[3]  # 744

lon <- ncvar_get(wbgt_inputs_aug_2019, "longitude")
lat <- ncvar_get(wbgt_inputs_aug_2019, "latitude")

cor_time <- sapply(
  1:ntime,
  function(t)
    cor(as.vector(atemp[,,t]),
        as.vector(wbgt[,,t]),
        use="complete.obs"))

# time series
plot(cor_time, type="l",
     ylab="Spatial correlation",
     xlab="Time index")
```
Time series shows how the spatial relationship between atemp and wbgt evolves through time.

look into this:
daytime → lower correlation (solar & humidity effects)
nighttime → higher correlation (temp dominates)


```{r}
# correlation across time at each grid cell -- FIGURE OUT ERROR

nlon  <- dim(atemp)[1]
nlat  <- dim(atemp)[2]
ntime <- dim(atemp)[3]

atemp_mat <- matrix(aperm(atemp, c(3,1,2)), nrow = ntime)
wbgt_mat <- matrix(aperm(wbgt, c(3,1,2)), nrow = ntime)

safe_cor <- function(x, y) {
  ok <- complete.cases(x, y)
  if (sum(ok) < 2) return(NA_real_)
  cor(x[ok], y[ok])}

cor_vals <- sapply(
  1:ncol(atemp_mat),
  function(k)
    cor(atemp_mat[,k],
        wbgt_mat[,k],
        use = "complete.obs"))

cor_map <- array(cor_vals, dim = c(nlon, nlat))

r_cor <- rast(t(cor_map))
ext(r_cor) <- c(min(lon), max(lon), min(lat), max(lat))
crs(r_cor) <- "EPSG:4326"

plot(r_cor)
```


