---
title: "calculate_wbgt_from_cimis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## calculate WBGT from CIMIS weather station data


```{r}
library(heatmetrics)
```

```{r}
# load CIMIS data for 2000
files <- list.files(path = "cimis_hourly/2000", pattern = "\\.csv$", recursive = TRUE, 
                    full.names = TRUE)
data_list <- lapply(files, read.csv)
```

# work with just Station 2 for now (January 2000)
```{r}
# create a look-up table
lookup <- data.frame(file = files, station = sapply(data_list, function(df) unique(df$Station)[1]))

# read station 2 file
station2 <- read.csv(lookup$file[lookup$station==2])

# subset station 2 file to just January 2000
library(dplyr)
station2_jan <- station2 |> mutate(Date = as.Date(Date)) |>  filter(format(Date, "%Y-%m") == "2000-01")
```

# Preprocess WBGT inputs for Jan 2000
```{r, warning=FALSE}
# note that missing values from CIMIS become NA in the preprocessed dataframe

# create dataframe for station 2 WBGT inputs
station2_inputs <- data.frame(row.names = seq_len(nrow(station2_jan)))

# year
station2_inputs$year <- as.integer(format(as.Date(station2_jan$Date), "%Y"))

# month
station2_inputs$month <- as.integer(format(as.Date(station2_jan$Date), "%m"))

# day
station2_inputs$day <- as.integer(format(as.Date(station2_jan$Date), "%d"))

# hour
station2_inputs$hour <- station2_jan$Hour/100 - 1

# dday
station2_inputs$dday <- station2_jan$Julian + (station2_jan$Hour/100 - 1) / 24

# lat
station2_inputs$lat <- as.numeric(sub(".* / ", "", station2_jan$latitude))

# lon
station2_inputs$lon <- as.numeric(sub(".* /", "", station2_jan$longitude))

# solar
station2_inputs$solar <- as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", station2_jan$HlySolRad))

# cza: caluclate using heatmetrics calc_cza_int()
station2_inputs$cza <- calc_cza_int(station2_inputs$lat, station2_inputs$lon, station2_inputs$year,
                                    station2_inputs$month, station2_inputs$day, station2_inputs$hour)

# fdir: use calc_fdir() function from heatmetrics
station2_inputs$fdir <- mapply(calc_fdir, station2_inputs$year, station2_inputs$month,
                               station2_inputs$day, station2_inputs$lat, station2_inputs$lon,
                               station2_inputs$solar, station2_inputs$cza)

# (for sensitivity analysis) fdir: derive from ERA5 and use calc_solar_parameters()
# library(terra)
# fdir_W <- rast("era5_2000_01_nn.nc", subds = "fdir") / 3600 # ERA5 direct solar radiation (W/m2)
# ssrd_W <- rast("era5_2000_01_nn.nc", subds = "ssrd") / 3600 # ERA5 surface solar radiation (W/m2)
# fdir_frac <- ifel(is.na(ssrd_W), NA, ifel(ssrd_W > 0, fdir_W / ssrd_W, 0))
# point <- vect(data.frame(lon = station2_inputs$lon[1], lat = station2_inputs$lat[1]), 
#               geom = c("lon", "lat"), crs = "EPSG:4326")
# ssrd_vals <- as.numeric(extract(ssrd_W, point)[1, -1])[-1] # drop first hour of ERA5 to match station2
# fdir_frac_vals <- as.numeric(extract(fdir_frac, point)[1, -1])[-1]
# solar_params_list <- mapply(calc_solar_parameters, station2_inputs$year, station2_inputs$month, 
#                                            station2_inputs$dday, station2_inputs$lat, 
#                                            station2_inputs$lon, ssrd_vals, 
#                                            station2_inputs$cza, fdir_frac_vals)
# station2_inputs$fdir2 <- solar_params_list["fdir", ]

# pres: calculate barometric pressure (hPa) from elevation in meters
elev_m <- station2_jan$elevation_ft * 0.3048
station2_inputs$pres <- 1013.25*(1+(-0.0065/288.15)*(elev_m))^(-9.80665*0.0289644/(8.31432*-0.0065))

# (for sensitivity analysis) pres: take sp from ERA5-Land (divide by 100 to get units in hPa)
# Open the ERA5_land for 2000_01, get surface pressure variable (sp)
# sp <- rast("era5_land_2000_01.nc", subds = "sp")
# point <- data.frame(x = station2_inputs$lon[1], y = station2_inputs$lat[1])
# station2_inputs$pres2 <- as.numeric(extract(sp, point)[1, -1])[-1] / 100 # drop first hr of ERA5-Land

# Tair
station2_inputs$Tair <- as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", station2_jan$HlyAirTmp))

# relhum
station2_inputs$relhum <- as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", station2_jan$HlyRelHum))

# speed
station2_inputs$speed <- as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", station2_jan$HlyWindSpd))

# zspeed
station2_inputs$zspeed <- 10

# dT
station2_inputs$dT <- -0.052

# urban: derived from NLCD on 0.1 degree grid
library(terra)
urban <- rast("deriving urban 0.01/urban_2000.nc")
point <- data.frame(x = station2_inputs$lon[1], y = station2_inputs$lat[1])
station2_inputs$urban <- ifelse(is.na(extract(urban, point)[1, 2]), 0, extract(urban, point)[1, 2])
```

## Test case
calculate WBGT for Jan 2000, and sensitivity analysis
```{r}
# loop WBGT calculation over rows of station2_inputs
station2_inputs$wbgt <- mapply(
  wbgt,
  station2_inputs$year,
  station2_inputs$month,
  station2_inputs$dday,
  station2_inputs$lat,
  station2_inputs$lon,
  station2_inputs$solar,
  station2_inputs$cza,
  station2_inputs$fdir,
  station2_inputs$pres,
  station2_inputs$Tair,
  station2_inputs$relhum,
  station2_inputs$speed,
  station2_inputs$zspeed,
  station2_inputs$dT,
  station2_inputs$urban
)

# with fdir2
station2_inputs$wbgt2 <- mapply(
  wbgt,
  station2_inputs$year,
  station2_inputs$month,
  station2_inputs$dday,
  station2_inputs$lat,
  station2_inputs$lon,
  station2_inputs$solar,
  station2_inputs$cza,
  station2_inputs$fdir2,
  station2_inputs$pres,
  station2_inputs$Tair,
  station2_inputs$relhum,
  station2_inputs$speed,
  station2_inputs$zspeed,
  station2_inputs$dT,
  station2_inputs$urban
)

# with pres2
station2_inputs$wbgt3 <- mapply(
  wbgt,
  station2_inputs$year,
  station2_inputs$month,
  station2_inputs$dday,
  station2_inputs$lat,
  station2_inputs$lon,
  station2_inputs$solar,
  station2_inputs$cza,
  station2_inputs$fdir,
  station2_inputs$pres2,
  station2_inputs$Tair,
  station2_inputs$relhum,
  station2_inputs$speed,
  station2_inputs$zspeed,
  station2_inputs$dT,
  station2_inputs$urban
)

# with fdir2 and pres2
station2_inputs$wbgt4 <- mapply(
  wbgt,
  station2_inputs$year,
  station2_inputs$month,
  station2_inputs$dday,
  station2_inputs$lat,
  station2_inputs$lon,
  station2_inputs$solar,
  station2_inputs$cza,
  station2_inputs$fdir2,
  station2_inputs$pres2,
  station2_inputs$Tair,
  station2_inputs$relhum,
  station2_inputs$speed,
  station2_inputs$zspeed,
  station2_inputs$dT,
  station2_inputs$urban
)

# compare two different WBGT values
diff <- station2_inputs$wbgt_4 - station2_inputs$wbgt

summary(diff)

sqrt(mean(diff^2, na.rm = TRUE))  # RMSE

# correlation
cor(station2_inputs$wbgt, station2_inputs$wbgt2, use = "complete.obs")
cor(station2_inputs$wbgt, station2_inputs$wbgt3, use = "complete.obs")
cor(station2_inputs$wbgt, station2_inputs$wbgt4, use = "complete.obs")

plot(station2_inputs$wbgt, station2_inputs$wbgt2, xlab = "WBGT", ylab = "WBGT with fdir2")
abline(0, 1, col = "red", lwd = 2)

plot(station2_inputs$wbgt, station2_inputs$wbgt3, xlab = "WBGT", ylab = "WBGT with pres2")
abline(0, 1, col = "red", lwd = 2)

plot(station2_inputs$wbgt, station2_inputs$wbgt4, xlab = "WBGT", ylab = "WBGT with fdir2, pres2")
abline(0, 1, col = "red", lwd = 2)
```


## Batch calculation (yearly station files)
CIMIS files one per station per year
```{r}
# load CIMIS data for all years 2000 to 2025
files <- list.files(path = "cimis_hourly", pattern = "\\.csv$", recursive = TRUE, full.names = TRUE)
```

```{r}
# loop through each year and calculate WBGT on all files
# save all inputs and WBGT in yearly files

library(terra)
library(heatmetrics)
library(purrr)

# load urban rasters
years <- 2000:2025
urban_cache <- setNames(
  lapply(years, function(y) {
    rast(paste0("urban_0.01/urban_", y, ".nc"))
  }),
  years)

process_station <- function(file){

  # Read station data
  dat <- read.csv(file)
  
  # read urban file
  file_year <- as.character(gsub(".*_(\\d{4})\\.csv", "\\1", file))
  urban <- urban_cache[[file_year]]
  
  # Create input dataframe
  inputs <- data.frame(row.names = seq_len(nrow(dat)))

  # get input variables
  inputs$year  <- as.integer(format(as.Date(dat$Date), "%Y"))
  inputs$month <- as.integer(format(as.Date(dat$Date), "%m"))
  inputs$day   <- as.integer(format(as.Date(dat$Date), "%d"))
  inputs$hour  <- dat$Hour / 100 - 1
  inputs$dday <- inputs$day + inputs$hour / 24
  inputs$lat <- as.numeric(sub(".* / ", "", dat$latitude))
  inputs$lon <- as.numeric(sub(".* / ", "", dat$longitude))
  inputs$solar <- suppressWarnings(as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", dat$HlySolRad)))
  inputs$Tair  <- suppressWarnings(as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", dat$HlyAirTmp)))
  inputs$relhum <- suppressWarnings(as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", dat$HlyRelHum)))
  inputs$speed <- suppressWarnings(as.numeric(sub(".*'Value': '(-?[0-9.]+)'.*", "\\1", dat$HlyWindSpd)))
  inputs$elev_m <- dat$elevation_ft * 0.3048

  # need to drop rows with missing inputs because CIMIS has some missing values
  inputs <- inputs[complete.cases(inputs), ]
  
  inputs$cza <- calc_cza_int(inputs$lat, inputs$lon, inputs$year, inputs$month, inputs$day,
                             inputs$hour)
  inputs$fdir <- mapply(calc_fdir, inputs$year, inputs$month, inputs$day, inputs$lat, inputs$lon,
                        inputs$solar, inputs$cza)
  inputs$pres <- 1013.25*(1+(-0.0065/288.15)*inputs$elev_m)^(-9.80665 * 0.0289644 / (8.31432 * -0.0065))
  inputs$zspeed <- 10
  inputs$dT <- -0.052
  point <- data.frame(x = inputs$lon[1], y = inputs$lat[1])
  u <- extract(urban, point)[1,2]
  inputs$urban <- ifelse(is.na(u), 0, u)
  
  # Calculate WBGT
  inputs$wbgt <- pmap_dbl(
  list(
    inputs$year,
    inputs$month,
    inputs$dday,
    inputs$lat,
    inputs$lon,
    inputs$solar,
    inputs$cza,
    inputs$fdir,
    inputs$pres,
    inputs$Tair,
    inputs$relhum,
    inputs$speed,
    inputs$zspeed,
    inputs$dT,
    inputs$urban
  ),
  wbgt)
  
  # Create output file name preserving folder structure
  outfile <- sub("^cimis_hourly", "CIMIS_WBGT", file)
  # Create output directory if it doesn't exist
  dir.create(dirname(outfile), recursive = TRUE, showWarnings = FALSE)
  # Save "inputs" (includes WBGT)
  write.csv(inputs, outfile, row.names = FALSE)
}

# Calculate WBGT on all CIMIS files -- skip files that were already processed
for (f in files) {
  outfile <- sub("^cimis_hourly", "CIMIS_WBGT", f)
  if (file.exists(outfile)) {
    cat("Skipping (already exists):", outfile, "\n")
    next
  }
  cat("Processing:", f, "\n")
  process_station(f)
}
```




