---
title: "inputs preprocessing part 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, results='asis', message=FALSE, warning=FALSE, collapse=TRUE)
```

```{r}
library(ncdf4)
library(terra)
library(reticulate)
```

###  checking preprocessed files
```{r}
# open the part 2 preprocessed file
inputs_p2 <- nc_open("wbgt_inputs_2000_01.nc") 

names(inputs_p2$var)
dim(ncvar_get(inputs_p2, "fdir_frac")) # R shows dimensions as longitude x latitude x times
ncatt_get(inputs_p2, "valid_time", "units")
```

```{r}
shp <- vect("deriving urban/ca_grid/ERA5_Land_grid_CAfull.shp")

r <- rast("wbgt_inputs_2000_01.nc", subds = "ssrd_W")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "ssrd_W at 2000-01-01 18:00 (CA cropped)", line = 3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "fdir_frac")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "fdir_frac at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "pres")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "pres at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "Tair")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "Tair at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "relhum")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "relhum at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "speed")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "speed at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "urban")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "urban at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "v_cza")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "v_cza at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "v_fdir")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "v_fdir at 2000-01-01 18:00", line=3)

r <- rast("wbgt_inputs_2000_01.nc", subds = "v_solarRet")
time_raw <- ncvar_get(inputs_p2, "valid_time")
time_vals <- as.POSIXct(time_raw, origin = "1970-01-01", tz = "UTC")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2000-01-01 18:00", tz="UTC"))
r_slice <- r[[t_index]]
r_crop <- crop(r_slice, shp)
r_mask <- mask(r_crop, shp)
plot(r_mask)
title(main = "v_solarRet at 2000-01-01 18:00", line=3)

nc_close(inputs_p2)
```



