---
title: "calculate_wbgt_aug_2019"
output: html_document
date: "2026-02-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(heatmetrics)
ls("package:heatmetrics") # functions in the heatmetrics package
```

```{r}
library(ncdf4)
library(terra)
library(parallel)
```

```{r}
# open netCDF file of preprocessed input variables
inputs <- nc_open("wbgt_inputs_aug_2019_added.nc")
names(inputs$var)
dim(ncvar_get(inputs, "fdir")) # R shows dimensions as longitude x latitude x time
```

```{r}
# get inputs for heatmetrics WBGT function

year  <- ncvar_get(inputs, "year")  # dim = 744
month <- ncvar_get(inputs, "month") # dim = 744
dday  <- ncvar_get(inputs, "dday")  # dim = 744
lat <- ncvar_get(inputs, "latitude")  # dim = 96
lon <- ncvar_get(inputs, "longitude") # dim = 105
solar  <- aperm(ncvar_get(inputs, "solarRet"), c(3,2,1)) # dim = 744 x 96 x 105 for below variables
cza    <- aperm(ncvar_get(inputs, "cza"), c(3,2,1))
fdir   <- aperm(ncvar_get(inputs, "fdir"), c(3,2,1))
pres   <- aperm(ncvar_get(inputs, "pres"), c(3,2,1))
Tair   <- aperm(ncvar_get(inputs, "Tair"), c(3,2,1))
relhum <- aperm(ncvar_get(inputs, "relhum"), c(3,2,1))
speed  <- aperm(ncvar_get(inputs, "speed"), c(3,2,1))
zspeed <- 10
dT     <- -0.052
urban  <- aperm(ncvar_get(inputs, "urban"), c(3,2,1))
```

```{r}
##### IGNORE

# heatmetrics WBGT function accepts scalar inputs

# testing on one point this worked, so try to expand on this idea

t <- 100
i <- 50
j <- 50

wbgt_test <- wbgt(
  year[t],
  month[t],
  dday[t],
  lat[i],
  lon[j],
  solar[t,i,j],
  cza[t,i,j],
  fdir[t,i,j],
  pres[t,i,j],
  Tair[t,i,j],
  relhum[t,i,j],
  speed[t,i,j],
  zspeed,
  dT,
  urban[t,i,j]
)
```

```{r}
# parallel processing
# took about 20 minutes

grid_lat <- rep(lat, each = length(lon))
grid_lon <- rep(lon, times = length(lat))

wbgt_out <- array(NA_real_, dim = dim(solar))

wbgt_time_worker <- function(t) {

  solar_v  <- as.vector(solar[t,,])
  cza_v    <- as.vector(cza[t,,])
  fdir_v   <- as.vector(fdir[t,,])
  pres_v   <- as.vector(pres[t,,])
  Tair_v   <- as.vector(Tair[t,,])
  relhum_v <- as.vector(relhum[t,,])
  speed_v  <- as.vector(speed[t,,])
  urban_v  <- as.vector(urban[t,,])

  valid <- !is.na(solar_v) &
           !is.na(cza_v) &
           !is.na(fdir_v) &
           !is.na(pres_v) &
           !is.na(Tair_v) &
           !is.na(relhum_v) &
           !is.na(speed_v) &
           !is.na(urban_v)

  out <- rep(NA_real_, length(solar_v))

  if (any(valid)) {
    out[valid] <- mapply(
      wbgt,
      year[t],
      month[t],
      dday[t],
      grid_lat[valid],
      grid_lon[valid],
      solar_v[valid],
      cza_v[valid],
      fdir_v[valid],
      pres_v[valid],
      Tair_v[valid],
      relhum_v[valid],
      speed_v[valid],
      MoreArgs = list(zspeed = zspeed, dT = dT),
      urban_v[valid]
    )
  }
  matrix(out, nrow = length(lat), ncol = length(lon))
}

cl <- makeCluster(detectCores() - 1)

clusterExport(cl, c(
  "wbgt","solar","cza","fdir","pres",
  "Tair","relhum","speed","urban",
  "year","month","dday",
  "lat","lon",
  "grid_lat","grid_lon",
  "zspeed","dT"
))

wbgt_list <- parLapply(cl, 1:dim(solar)[1], wbgt_time_worker)

stopCluster(cl)

for (t in seq_along(wbgt_list)) {
  wbgt_out[t,,] <- wbgt_list[[t]]
}
```

```{r}
summary(wbgt_out)  # NA's are just the grid cells outside the shape of California
dim(wbgt_out)
```

```{r}
# plot wbgt_out at a single timestep

times <- as.POSIXct(ncvar_get(inputs, "valid_time"), origin = "1970-01-01", tz = "UTC")
t_index <- which(times == as.POSIXct("2019-08-01 18:00", tz="UTC"))
wbgt_slice <- wbgt_out[t_index,,]
r <- rast(wbgt_slice)
ext(r) <- c(min(lon), max(lon), min(lat), max(lat))
crs(r) <- "EPSG:4326"
if (lat[1] < lat[length(lat)]) r <- flip(r, "vertical")
plot(r)
title(main = paste("WBGT at", times[t_index]), line=3)
```

```{r}
# save wbgt_out as netCDF file---------DELETE

wbgt_out <- aperm(wbgt_out, c(3, 2, 1))

lon_dim  <- inputs$dim$longitude
lat_dim  <- inputs$dim$latitude
time_dim <- inputs$dim$valid_time

#lon_dim  <- ncdim_def("longitude",  "degrees_east",  lon)
#lat_dim  <- ncdim_def("latitude",  "degrees_north", lat)
#time_dim <- ncdim_def("valid_time", "seconds since 1970-01-01", time)

wbgt <- ncvar_def(
  name = "wbgt",
  units = "degrees_Celsius",
  dim = list(lon_dim, lat_dim, time_dim),
  missval = -9999,
  longname = "Wet-bulb globe temperature",
  prec = "float"
)

ncfile <- nc_create("wbgt_aug_2019_new.nc", vars = wbgt)

ncvar_put(ncfile, wbgt, wbgt_out)

nc_close(ncfile)
```

```{r}
# open wbgt_aug_2019_new.nc to check----------DELETE

wbgt_aug_2019_new <- nc_open("wbgt_aug_2019_new.nc")
names(wbgt_aug_2019_new$var)
dim(ncvar_get(wbgt_aug_2019_new, "wbgt")) # R shows dimensions as longitude x latitude x time
```






```{r}
# save wbgt_out as netCDF file ----THIS WORKED

wbgt_out <- aperm(wbgt_out, c(3, 2, 1))

lon_dim  <- ncdim_def("longitude",  "degrees_east",  lon)
lat_dim  <- ncdim_def("latitude",  "degrees_north", lat)
time_num <- as.numeric(times)
time_dim <- ncdim_def("valid_time", "seconds since 1970-01-01", time_num)

wbgt <- ncvar_def(
  name = "wbgt",
  units = "degrees_Celsius",
  dim = list(lon_dim, lat_dim, time_dim),
  missval = -9999,
  longname = "Wet-bulb globe temperature",
  prec = "float"
)

ncfile <- nc_create("wbgt_aug_2019_b.nc", wbgt)

ncvar_put(ncfile, wbgt, wbgt_out)

nc_close(ncfile)
```

```{r}
# open wbgt_aug_2019_b.nc to check

wbgt_aug_2019_b <- nc_open("wbgt_aug_2019_b.nc")
names(wbgt_aug_2019_b$var)
dim(ncvar_get(wbgt_aug_2019_b, "wbgt")) # R shows dimensions as longitude x latitude x time
```
```{r}
# plot from the file to check (plot in CA time)

times_utc <- as.POSIXct(
  wbgt_aug_2019_b$dim$valid_time$vals,
  origin = "1970-01-01",
  tz = "UTC"
)

times_ca <- with_tz(times_utc, "America/Los_Angeles")

# Choose a time (robust match)
target_time <- as.POSIXct("2019-08-01 18:00", tz="America/Los_Angeles")
t_index <- which.min(abs(times_ca - target_time))

# Load raster directly
r <- rast("wbgt_aug_2019_b.nc", subds = "wbgt")

# Plot
plot(r[[t_index]])
title(main = paste("WBGT at", format(times_ca[t_index], "%Y-%m-%d %H:%M %Z")), line=3)
```


