---
title: "compare_wbgt_with_heatmetrics"
output: html_document
date: "2026-02-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ncdf4)
library(terra)
library(tigris)
library(sf)
library(ggplot2)
library(lubridate)
library(exactextractr)
```

```{r}
# load heatmetrics data (from Spangler et al.)
heatvars <- readRDS("UNWEIGHTED_Heatvars_County_2000-2020_v1.2.Rds")

# select August 2019 from heatmetrics data
heatvars_aug_2019 <- subset(heatvars, Date >= "2019-08-01" & Date <= "2019-08-31")

# load wbgt_aug_2019
wbgt_aug_2019_b <- nc_open("wbgt_aug_2019_b.nc")

# "wbgt_aug_2019.nc" time is in "seconds since 1970-01-01" --> POSIX time (a form of UTC time)
ncatt_get(wbgt_aug_2019_b, "valid_time", "units")$value
```

```{r}
names(wbgt_aug_2019_b$var)
dim(ncvar_get(wbgt_aug_2019_b, "wbgt")) # R shows dimensions as longitude x latitude x time
```

```{r}
# plot heatmetrics WBGTmin_C, WBGTmax_C, WBGTmean_C variables for a Aug 1, 2019

heatvars_aug_1_2019 <- subset(heatvars, Date == "2019-08-01")

counties_sf <- counties(cb = TRUE, year = 2020) %>%  st_as_sf()
map_data <- counties_sf %>% left_join(heatvars_aug_1_2019, by = c("GEOID" = "StCoFIPS"))
ca_map <- map_data %>% filter(STATEFP == "06")  # plot only California

# Lowest wet-bulb globe temperature (WBGT) observed from hourly data from 00 LST to 23 LST
ggplot(ca_map) + geom_sf(aes(fill = WBGTmin_C), color = NA) + 
  scale_fill_viridis_c(name = "minimum WBGT (C)") + theme_minimal() +
  labs(title = "Minimum WBGT by County", subtitle = "August 1, 2019")

# Highest wet-bulb globe temperature (WBGT) observed from hourly data from 00 LST to 23 LST
ggplot(ca_map) + geom_sf(aes(fill = WBGTmax_C), color = NA) + 
  scale_fill_viridis_c(name = "maximum WBGT (C)") + theme_minimal() +
  labs(title = "Maximum WBGT by County", subtitle = "August 1, 2019")
	
# Wet-bulb globe temperature (WBGT) averaged over hourly observations from 00 LST to 23 LST
ggplot(ca_map) + geom_sf(aes(fill = WBGTmean_C), color = NA) + 
  scale_fill_viridis_c(name = "mean WBGT (C)") + theme_minimal() +
  labs(title = "Mean WBGT by County", subtitle = "August 1, 2019")
```
```{r}
# check values of wbgt
var <- ncvar_get(wbgt_aug_2019_b, "wbgt")
summary(as.vector(var)) # as.vector flattens multi-dimensional data
```

```{r}
# Plot WBGT in CA local time

times_utc <- as.POSIXct(ncvar_get(wbgt_aug_2019_b, "valid_time"), origin = "1970-01-01", tz = "UTC")
times_ca <- with_tz(times_utc, "America/Los_Angeles")
t_index <- which(times_ca == as.POSIXct("2019-08-01 18:00", tz = "America/Los_Angeles"))

# plot of wet-bulb globe temp at a single valid_time
r <- rast("wbgt_aug_2019_b.nc", subds = "wbgt")
plot(r[[t_index]])
title(main = paste("WBGT at", format(times_ca[t_index], "%Y-%m-%d %H:%M %Z")), line=3)


#r <- rast("wbgt_aug_2019_new.nc", subds = "wbgt")
#r <- flip(r, "vertical")
#plot(r[[t_index]])
#title(main = paste("WBGT at", format(times_ca[t_index], "%Y-%m-%d %H:%M %Z")), line=3)
```

```{r}
# plot county-level WBGT for Aug 1, 2019 from wbgt_aug_2019_new.nc

# calculate the daily mean for each grid cell and then calculated the county-level mean by overlaying the county shape file

times_utc <- as.POSIXct(ncvar_get(wbgt_aug_2019_b, "valid_time"), origin = "1970-01-01", tz = "UTC")
times_ca <- with_tz(times_utc, "America/Los_Angeles")
day_index <- which(as.Date(times_ca) == as.Date("2019-08-01"))

r <- rast("wbgt_aug_2019_b.nc", subds = "wbgt")

r_day <- mean(r[[day_index]])  # compute daily mean per grid cell

ca_counties <- counties(state = "CA", cb = TRUE, year = 2020) %>%  st_as_sf()
ca_counties <- st_transform(ca_counties, crs(r_day))  # make CRS of ca_counties match CRS of r_day

county_means <- terra::extract(r_day, vect(ca_counties), fun = mean, 
                               weights = TRUE, na.rm = TRUE)

ca_counties$WBGT_mean <- county_means[,2]

# plot
ggplot(ca_counties) +
  geom_sf(aes(fill = WBGT_mean), color=NA) +
  scale_fill_viridis_c(name = "Daily Mean WBGT (°C)") +
  theme_minimal() +
  labs(title = "County-Level Daily Mean WBGT", subtitle = "2019-08-01")
```

```{r}
# plot with same color scale to compare

common_limits <- range(c(ca_map$WBGTmean_C, ca_counties$WBGT_mean))

# from heatvars
ggplot(ca_map) + 
  geom_sf(aes(fill = WBGTmean_C), color = NA) + 
  scale_fill_viridis_c(name = "mean WBGT (C)", limits = common_limits) +
  theme_minimal() + labs(title = "Mean WBGT by County", subtitle = "August 1, 2019")

# from wbgt calculation
ggplot(ca_counties) +
  geom_sf(aes(fill = WBGT_mean), color = NA) +
  scale_fill_viridis_c(name = "Daily Mean WBGT (°C)", limits = common_limits) +
  theme_minimal() +  labs(title = "County-Level Daily Mean WBGT", subtitle = "2019-08-01")


# how much they differ
library(dplyr)

comparison <- ca_counties %>%
  st_drop_geometry() %>%
  dplyr::select(GEOID, WBGT_mean) %>%
  left_join(
    ca_map %>%
      st_drop_geometry() %>%
      dplyr::select(GEOID, WBGTmean_C),
    by = "GEOID")

comparison <- comparison %>%
  mutate(diff_C = WBGT_mean - WBGTmean_C)

summary(comparison$diff_C)

ggplot(comparison, aes(x = WBGTmean_C, y = WBGT_mean)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
  geom_smooth(method = "lm", color = "blue") +
  theme_minimal() +
  labs(
    x = "Spangler WBGT",
    y = "My WBGT",
    title = "Comparison of County WBGT Values",
    subtitle = "Red = 1:1 line, Blue = regression")
```


```{r}
# correlation: ca_counties vs ca_map
ca_map <- st_transform(ca_map, crs(ca_counties))  # make CRS of ca_map match CRS of ca_counties

# comparing WBGT county-level mean for Aug 1, 2019
comparison <- ca_counties |> st_drop_geometry() |>
  dplyr::select(GEOID, calculated_WBGT_mean = WBGT_mean) |>
  dplyr::left_join(
    ca_map |>  st_drop_geometry() |>
      dplyr::select(GEOID, heatvars_WBGT_mean = WBGTmean_C), by = "GEOID")

# correlation and RMSE
correlation <- cor(comparison$heatvars_WBGT_mean, comparison$calculated_WBGT_mean)
paste("correlation coefficient: ", correlation)
rmse <- sqrt(mean((comparison$heatvars_WBGT_mean - comparison$heatvars_WBGT_mean)^2))
paste("RMSE: ", rmse)

# scatterplot
ggplot(comparison, aes(x = heatvars_WBGT_mean, y = calculated_WBGT_mean)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  theme_minimal() +
  labs(x = "heatvars WBGT county-level mean",
    y = "calculated WBGT county-level mean",
    title = "County-Level Comparison for 2019-08-01")
```



