---
title: "vect_calculate_cza_and_fdir_aug_2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, results='asis', message=FALSE, warning=FALSE, collapse=TRUE)
```

```{r}
library(heatmetrics)
ls("package:heatmetrics") # functions in the heatmetrics package
```

```{r}
library(ncdf4)
library(terra)
library(reticulate)
```

```{r}
# open and view preprocessed dataset
wbgt_inputs_aug_2019_new <- nc_open("wbgt_inputs_aug_2019_new.nc", write = TRUE)
names(wbgt_inputs_aug_2019_new$var)
dim(ncvar_get(wbgt_inputs_aug_2019_new, "solar"))
# R shows dimensions as longitude x latitude x times
```


## Calculate "cza" using v_calc_cza_int
```{r}
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_calc_cza.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_calc_cza_int.R")

# make grid
lon_grid <- matrix(rep(lon, each = length(lat)), nrow = length(lat))
lat_grid <- matrix(rep(lat, times = length(lon)), nrow = length(lat))

# preallocate output array
ntime <- length(year)
nlat  <- length(lat)
nlon  <- length(lon)

v_cza_array <- array(NA, dim = c(nlat, nlon, ntime))

# get inputs
lat <- ncvar_get(wbgt_inputs_aug_2019_new, "latitude")
lon <- ncvar_get(wbgt_inputs_aug_2019_new, "longitude")
year  <- ncvar_get(wbgt_inputs_aug_2019_new, "year")
month <- ncvar_get(wbgt_inputs_aug_2019_new, "month")
day   <- ncvar_get(wbgt_inputs_aug_2019_new, "day")
hour  <- ncvar_get(wbgt_inputs_aug_2019_new, "hour")

# apply function over time (vectorized function takes grid input and outputs a grid of values)
cza_list <- lapply(seq_len(ntime), function(t) {
  v_calc_cza_int(
    lat_grid,
    lon_grid,
    year[t],
    month[t],
    day[t],
    hour[t]
  )
})

v_cza_array <- simplify2array(cza_list)
v_cza_array <- aperm(v_cza_array, c(2, 1, 3))
```

```{r}
# check that dimensions of v_cza_array match dimensions of wbgt_inputs_aug_2019
dim(ncvar_get(wbgt_inputs_aug_2019_new, "solar"))
dim(v_cza_array)  # longitude x latitude x time

summary(v_cza_array) # check that all values are in [0,1]

# plot v_cza_array
times <- as.POSIXct(ncvar_get(wbgt_inputs_aug_2019_new, "valid_time"), origin = "1970-01-01", tz = "UTC")
t_index <- which(times == as.POSIXct("2019-08-01 18:00", tz="UTC"))
r_cza <- rast(aperm(v_cza_array, c(2,1,3)))
ext(r_cza) <- c(min(lon), max(lon), min(lat), max(lat))
crs(r_cza) <- "EPSG:4326"
plot(r_cza[[t_index]])
title(main = paste("cza at", times[t_index]), line=3)
```


## Calculating "fdir" and "solarRet" input using v_calc_solar_parameters

```{r}
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_calc_solar_parameters.R")

# get inputs
lat <- ncvar_get(wbgt_inputs_aug_2019_new, "latitude")
lon <- ncvar_get(wbgt_inputs_aug_2019_new, "longitude")
year  <- ncvar_get(wbgt_inputs_aug_2019_new, "year")
month <- ncvar_get(wbgt_inputs_aug_2019_new, "month")
day   <- ncvar_get(wbgt_inputs_aug_2019_new, "dday")
hour <- ncvar_get(wbgt_inputs_aug_2019_new, "hour")
solar <- ncvar_get(wbgt_inputs_aug_2019_new, "ssrd_hr_W")  # hourly ERA5-Land ssrd in W/m2
cza <- ncvar_get(wbgt_inputs_aug_2019_new, "cza")  # calculated from calc_cza_int()
fdir <- ncvar_get(wbgt_inputs_aug_2019_new, "fdir_frac") # (NN-inter ERA5 fdir)/(hourly ERA5-Land ssrd)

# make grid
lon_grid <- matrix(rep(lon, each = length(lat)), nrow = length(lat))
lat_grid <- matrix(rep(lat, times = length(lon)), nrow = length(lat))

# preallocate output array
ntime <- length(year)
nlat  <- length(lat)
nlon  <- length(lon)

v_solarRet_array <- array(NA, dim = c(nlat, nlon, ntime))
v_fdir_array <- array(NA, dim = c(nlat, nlon, ntime))


# apply function over time (vectorized function takes grid input and outputs a grid of values)
solar_params_list <- lapply(seq_len(ntime), function(t) {

  v_calc_solar_parameters(
    year  = year[t],
    month = month[t],
    day   = day[t],
    hour  = hour[t],
    lat   = lat_grid,
    lon   = lon_grid,
    solar = solar[,,t],
    cza   = cza[,,t],
    fdir  = fdir[,,t]
  )
})

v_solarRet_array <- simplify2array(lapply(solar_params_list, `[[`, "solarRet"))
v_fdir_array     <- simplify2array(lapply(solar_params_list, `[[`, "fdir"))
```

```{r}
# check that dimensions of v_solarRet_array and v_fdir_array match dims of wbgt_inputs_aug_2019_new
dim(ncvar_get(wbgt_inputs_aug_2019_new, "solar"))
dim(v_fdir_array)  # longitude x latitude x time

options(digits = 10)
summary(v_solarRet_array)
summary(v_fdir_array, digits = 10)


# plot v_solarRet_array
times <- as.POSIXct(ncvar_get(wbgt_inputs_aug_2019_new, "valid_time"), origin = "1970-01-01", tz = "UTC")
t_index <- which(times == as.POSIXct("2019-08-01 03:00", tz="UTC"))
r_solarRet <- rast(aperm(v_solarRet_array, c(2,1,3)))
ext(r_solarRet) <- c(min(lon), max(lon), min(lat), max(lat))
crs(r_solarRet) <- "EPSG:4326"
plot(r_solarRet[[t_index]])
title(main = paste("solarRet at", times[t_index]), line=3)

# plot v_fdir_array
times <- as.POSIXct(ncvar_get(wbgt_inputs_aug_2019_new, "valid_time"), origin = "1970-01-01", tz = "UTC")
t_index <- which(times == as.POSIXct("2019-08-01 03:00", tz="UTC"))
r_fdir <- rast(aperm(v_fdir_array, c(2,1,3)))
ext(r_fdir) <- c(min(lon), max(lon), min(lat), max(lat))
crs(r_fdir) <- "EPSG:4326"
plot(r_fdir[[t_index]])
title(main = paste("fdir at", times[t_index]), line=3)
```


## Save v_cza, v_fdir, and v_solarRet to the inputs dataset

```{r}
#### create temporary file to hold v_cza, v_fdir, and v_solarRet

# define dimensions
dim_lon  <- ncdim_def("longitude","degrees_east",wbgt_inputs_aug_2019_new$dim$longitude$vals)
dim_lat  <- ncdim_def("latitude","degrees_north",wbgt_inputs_aug_2019_new$dim$latitude$vals)
dim_time <- ncdim_def("valid_time","seconds since 1970-01-01",
                      wbgt_inputs_aug_2019_new$dim$valid_time$vals)

# define variables

v_cza <- ncvar_def(
  name = "v_cza",
  units = "",
  dim = list(dim_lon, dim_lat, dim_time),
  missval = -9999,
  longname = "cosine solar zenith angle (0-1)",
  prec = "float")
v_fdir <- ncvar_def(
  name = "v_fdir",
  units = "",   # no units because it's a ratio
  dim = list(dim_lon, dim_lat, dim_time),
  missval = -9999,
  longname = "Fraction of irradiance due to direct beam (0-1)",
  prec = "float")
v_solarRet <- ncvar_def(
  name = "v_solarRet",
  units = "W m**-2",
  dim = list(dim_lon, dim_lat, dim_time),
  missval = -9999,
  longname = "adjusted solar radiation",
  prec = "float")

# create temporary NetCDF with only new variables
nc_temp <- nc_create("temp2.nc", list(v_cza, v_fdir, v_solarRet))
ncvar_put(nc_temp, "v_cza", v_cza_array)
ncvar_put(nc_temp, "v_fdir", v_fdir_array)
ncvar_put(nc_temp, "v_solarRet", v_solarRet_array)
nc_close(nc_temp)
nc_close(wbgt_inputs_aug_2019_new)
```

```{r}
# view temp2.nc
temp2 <- nc_open("temp2.nc")
names(temp2$var)
dim(ncvar_get(temp2, "v_fdir"))
nc_close(temp2)
```

```{python}
# add v_cza, v_fdir, and v_solarRet to the inputs dataset and save as new file

import xarray as xr

ds = xr.open_dataset("wbgt_inputs_aug_2019_added.nc")

temp = xr.open_dataset("temp2.nc")

# add fdir variable to dataset ----- FIX
ds["v_cza"] = temp["v_cza"]
ds["v_fdir"] = temp["v_fdir"]
ds["v_solarRet"] = temp["v_solarRet"]

# save as a new file
ds.to_netcdf("wbgt_inputs_aug_2019_updated.nc")

# close files
ds.close()
temp.close()
```

```{r}
# verify that they were added

nc <- nc_open("wbgt_inputs_aug_2019_updated.nc")
names(nc$var)         # should now include "v_cza", "v_fdir", "v_solarRet"
dim(ncvar_get(nc, "fdir"))
nc_close(nc)
```

```{r}
# just checking

nc <- nc_open("wbgt_inputs_aug_2019_updated.nc")

time_raw <- ncvar_get(nc, "valid_time")
time_units <- ncatt_get(nc, "valid_time", "units")$value
time_vals <- as.POSIXct(time_raw, origin="1970-01-01", tz="UTC")

r <- rast("wbgt_inputs_aug_2019_updated.nc", subds = "v_cza")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2019-08-01 18:00", tz="UTC"))
plot(r[[t_index]])
title(main = "v_cza at 2019-08-01 18:00", line=3)

r <- rast("wbgt_inputs_aug_2019_updated.nc", subds = "v_fdir")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2019-08-01 18:00", tz="UTC"))
plot(r[[t_index]])
title(main = "v_fdir at 2019-08-01 18:00", line=3)

r <- rast("wbgt_inputs_aug_2019_updated.nc", subds = "v_solarRet")
time(r) <- time_vals
t_index <- which(time_vals == as.POSIXct("2019-08-01 18:00", tz="UTC"))
plot(r[[t_index]])
title(main = "v_solarRet at 2019-08-01 18:00", line=3)

nc_close(nc)
```



