---
title: "v_calculate_wbgt_aug_2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, results='asis', message=FALSE, warning=FALSE, collapse=TRUE)
```

```{r}
library(heatmetrics)
ls("package:heatmetrics") # functions in the heatmetrics package
```

```{r}
library(ncdf4)
library(terra)
library(reticulate)
library(parallel)
library(dplyr)
library(tigris)
library(sf)
library(ggplot2)
library(lubridate)
library(exactextractr)
```

```{r}
# open and view preprocessed dataset
inputs <- nc_open("wbgt_inputs_aug_2019_updated.nc")
names(inputs$var)
dim(ncvar_get(inputs, "ssrd_W"))
# R shows dimensions as longitude x latitude x times
```

```{r}
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_calc_solar_parameters.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_stab_srdt.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_est_wind_speed.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_esat.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_emis_atm.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_h_sphere_in_air.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_Tglobe.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_dew_point.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_h_cylinder_in_air.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_Twb.R")
source("C:/Users/new account/Desktop/WBGT-heat-project/heatmetrics_vec/v_wbgt.R")
```


## calculate wbgt with vectorized function

```{r}
# get inputs for WBGT function

year  <- ncvar_get(inputs, "year")  # dim = 744
month <- ncvar_get(inputs, "month") # dim = 744
dday  <- ncvar_get(inputs, "dday")  # dim = 744
lat <- ncvar_get(inputs, "latitude")  # dim = 96
lon <- ncvar_get(inputs, "longitude") # dim = 105
solar  <- aperm(ncvar_get(inputs, "v_solarRet"), c(3,2,1)) # dim = 744 x 96 x 105 for below variables
cza    <- aperm(ncvar_get(inputs, "v_cza"), c(3,2,1))
fdir   <- aperm(ncvar_get(inputs, "v_fdir"), c(3,2,1))
pres   <- aperm(ncvar_get(inputs, "pres"), c(3,2,1))
Tair   <- aperm(ncvar_get(inputs, "Tair"), c(3,2,1))
relhum <- aperm(ncvar_get(inputs, "relhum"), c(3,2,1))
speed  <- aperm(ncvar_get(inputs, "speed"), c(3,2,1))
zspeed <- 10
dT     <- -0.052
urban  <- aperm(ncvar_get(inputs, "urban"), c(3,2,1))
```

Calculate with new fdir
```{r}
# --- precompute grids ---
nlat <- length(lat)
nlon <- length(lon)
ntime <- dim(solar)[1]

lat_mat <- matrix(lat, nrow = nlat, ncol = nlon)
lon_mat <- matrix(lon, nrow = nlat, ncol = nlon, byrow = TRUE)

# --- output array ---
wbgt_out <- array(NA_real_, dim = dim(solar))

# --- loop calculation over time ---
system.time({
for (t in 1:ntime) {

  # expand time variables
  year_mat  <- matrix(year[t],  nlat, nlon)
  month_mat <- matrix(month[t], nlat, nlon)
  dday_mat  <- matrix(dday[t],  nlat, nlon)

  # call vectorized WBGT
  wbgt_out[t,,] <- v_wbgt(
    year_mat, month_mat, dday_mat,
    lat_mat, lon_mat,
    solar[t,,], cza[t,,], fdir[t,,],
    pres[t,,], Tair[t,,], relhum[t,,],
    speed[t,,], zspeed, dT, urban[t,,]
  )}
})
```

```{r}
# crop to California shape

times <- as.POSIXct(ncvar_get(inputs, "valid_time"), origin = "1970-01-01", tz = "UTC")
wbgt_for_terra <- aperm(wbgt_out, c(2, 3, 1))
r_wbgt <- rast(wbgt_for_terra)
ext(r_wbgt) <- c(min(lon), max(lon), min(lat), max(lat))
crs(r_wbgt) <- "EPSG:4326"

# fix orientation if needed
#if (lat[1] < lat[length(lat)]) {
#  r_wbgt <- flip(r_wbgt, "vertical")
#}

ca_shape <- vect("ca_grid/ERA5_Land_grid_CAfull.shp")
ca_shape <- project(ca_shape, crs(r_wbgt))

r_wbgt <- crop(r_wbgt, ca_shape, snap="out")
r_wbgt_ca <- mask(r_wbgt, ca_shape)

#r_wbgt_ca <- crop(r_wbgt, ca_shape)
#r_wbgt_ca <- mask(r_wbgt_ca, ca_shape)

vals <- terra::values(r_wbgt_ca, mat = TRUE)

nrow_ca <- nrow(r_wbgt_ca)
ncol_ca <- ncol(r_wbgt_ca)
ntime <- nlyr(r_wbgt_ca)

# rebuild array in terra order: (lat × lon × time)
wbgt_ca <- array(vals, dim = c(ncol_ca, nrow_ca, ntime))

# convert back to original format: time × lat × lon
wbgt_ca <- aperm(wbgt_ca, c(3, 2, 1))
```

```{r}
summary(wbgt_ca)  # NA's should just be the grid cells outside the shape of California
dim(wbgt_ca)
```

```{r}
# plot wbgt_out at a single timestep

times <- as.POSIXct(ncvar_get(inputs, "valid_time"), origin = "1970-01-01", tz = "UTC")
t_index <- which(times == as.POSIXct("2019-08-01 18:00", tz="UTC"))
wbgt_slice <- wbgt_ca[t_index,,]
r <- rast(wbgt_slice)
ext(r) <- c(min(lon), max(lon), min(lat), max(lat))
crs(r) <- "EPSG:4326"
if (lat[1] < lat[length(lat)]) r <- flip(r, "vertical")
plot(r)
title(main = paste("WBGT at", times[t_index]), line=3)
```


## compare this WBGT output with previous WBGT

Calculate with old fdir
```{r}
# open and view preprocessed dataset
inputs_old <- nc_open("wbgt_inputs_aug_2019_old.nc") ## change dataset
names(inputs_old$var)
dim(ncvar_get(inputs_old, "solar"))
# R shows dimensions as longitude x latitude x times
```

```{r}
# get inputs for WBGT function

year  <- ncvar_get(inputs_old, "year")  # dim = 744
month <- ncvar_get(inputs_old, "month") # dim = 744
dday  <- ncvar_get(inputs_old, "dday")  # dim = 744
lat <- ncvar_get(inputs_old, "latitude")  # dim = 96
lon <- ncvar_get(inputs_old, "longitude") # dim = 105
solar  <- aperm(ncvar_get(inputs_old, "v_solarRet"), c(3,2,1)) # dim = 744 x 96 x 105 for below
cza    <- aperm(ncvar_get(inputs_old, "v_cza"), c(3,2,1))
fdir   <- aperm(ncvar_get(inputs_old, "v_fdir"), c(3,2,1))
pres   <- aperm(ncvar_get(inputs_old, "pres"), c(3,2,1))
Tair   <- aperm(ncvar_get(inputs_old, "Tair"), c(3,2,1))
relhum <- aperm(ncvar_get(inputs_old, "relhum"), c(3,2,1))
speed  <- aperm(ncvar_get(inputs_old, "speed"), c(3,2,1))
zspeed <- 10
dT     <- -0.052
urban  <- aperm(ncvar_get(inputs_old, "urban"), c(3,2,1))
```

```{r}
# --- precompute grids ---
nlat <- length(lat)
nlon <- length(lon)
ntime <- dim(solar)[1]

lat_mat <- matrix(lat, nrow = nlat, ncol = nlon)
lon_mat <- matrix(lon, nrow = nlat, ncol = nlon, byrow = TRUE)

# --- output array ---
wbgt_out_old <- array(NA_real_, dim = dim(solar))

# --- loop calculation over time ---
system.time({
for (t in 1:ntime) {

  # expand time variables
  year_mat  <- matrix(year[t],  nlat, nlon)
  month_mat <- matrix(month[t], nlat, nlon)
  dday_mat  <- matrix(dday[t],  nlat, nlon)

  # call vectorized WBGT
  wbgt_out_old[t,,] <- v_wbgt(
    year_mat, month_mat, dday_mat,
    lat_mat, lon_mat,
    solar[t,,], cza[t,,], fdir[t,,],
    pres[t,,], Tair[t,,], relhum[t,,],
    speed[t,,], zspeed, dT, urban[t,,]
  )}
})
```

```{r}
summary(wbgt_out_old)  # NA's should just be the grid cells outside the shape of California
dim(wbgt_out_old)
```

## Comparisons
```{r}
# save wbgt_ca and wbgt_out_old to a file

# define dimensions
dim_lon  <- ncdim_def("longitude","degrees_east",wbgt_inputs_aug_2019$dim$longitude$vals)
dim_lat  <- ncdim_def("latitude","degrees_north",wbgt_inputs_aug_2019$dim$latitude$vals)
dim_time <- ncdim_def("valid_time","seconds since 1970-01-01",
                      wbgt_inputs_aug_2019$dim$valid_time$vals)

# define variables

wbgt_new <- ncvar_def(
  name = "wbgt_new",
  units = "degrees_Celsius",
  dim = list(dim_lon, dim_lat, dim_time),
  missval = -9999,
  longname = "Wet-bulb globe temperature",
  prec = "float")
wbgt_old <- ncvar_def(
  name = "wbgt_old",
  units = "degrees_Celsius", 
  dim = list(dim_lon, dim_lat, dim_time),
  missval = -9999,
  longname = "Wet-bulb globe temperature",
  prec = "float")

wbgt_ca <- aperm(wbgt_ca, c(3, 2, 1))  
wbgt_out_old <- aperm(wbgt_out_old, c(3, 2, 1))

# create NetCDF with wbgt_new and wbgt_old
wbgt_outputs <- nc_create("wbgt_outputs.nc", list(wbgt_new, wbgt_old))
ncvar_put(wbgt_outputs, "wbgt_new", wbgt_ca)
ncvar_put(wbgt_outputs, "wbgt_old", wbgt_out_old)
nc_close(wbgt_outputs)
nc_close(wbgt_inputs_aug_2019)
```

```{r}
# open wbgt_outputs.nc
wbgt_outputs <- nc_open("wbgt_outputs.nc")
names(wbgt_outputs$var)
ncatt_get(wbgt_outputs, "valid_time", "units")$value

# summary of values of wbgt_new
wbgt_new <- ncvar_get(wbgt_outputs, "wbgt_new")
summary(wbgt_new)  # NA's should just be the grid cells outside the shape of California
dim(wbgt_new)

# summary of values of wbgt_old
wbgt_old <- ncvar_get(wbgt_outputs, "wbgt_old")
summary(wbgt_old)  # NA's should just be the grid cells outside the shape of California
dim(wbgt_old)
```

```{r}
# compare wbgt_new with wbgt_old
# correlation and RMSE over all grid points and time
x <- as.vector(wbgt_new)
y <- as.vector(wbgt_old)
# Remove NA pairs
valid <- complete.cases(x, y)
x <- x[valid]
y <- y[valid]
# Correlation
correlation <- cor(x, y)
cat("correlation: ", correlation, "\n")
# RMSE
rmse <- sqrt(mean((x - y)^2))
cat("RMSE: ", rmse, "\n")
# bias
bias <- mean(wbgt_old - wbgt_new, na.rm = TRUE)
cat("bias: ", bias)
```
## compare with Spangler's

```{r}
# load heatmetrics data (from Spangler et al.)
heatvars <- readRDS("UNWEIGHTED_Heatvars_County_2000-2020_v1.2.Rds")

# select August 2019 from heatmetrics data
heatvars_aug_2019 <- subset(heatvars, Date >= "2019-08-01" & Date <= "2019-08-31")
```

```{r}
# plot heatmetrics WBGTmin_C, WBGTmax_C, WBGTmean_C variables for a Aug 1, 2019

heatvars_aug_1_2019 <- subset(heatvars, Date == "2019-08-01")

counties_sf <- counties(cb = TRUE, year = 2020) %>%  st_as_sf()
map_data <- counties_sf %>% left_join(heatvars_aug_1_2019, by = c("GEOID" = "StCoFIPS"))
ca_map <- map_data %>% filter(STATEFP == "06")  # plot only California
	
# Wet-bulb globe temperature (WBGT) averaged over hourly observations from 00 LST to 23 LST
ggplot(ca_map) + geom_sf(aes(fill = WBGTmean_C), color = NA) + 
  scale_fill_viridis_c(name = "mean WBGT (C)") + theme_minimal() +
  labs(title = "Mean WBGT by County", subtitle = "August 1, 2019")
```

```{r}
# Plot WBGT in CA local time

times_utc <- as.POSIXct(wbgt_outputs$dim$valid_time$vals, origin = "1970-01-01", tz = "UTC")
times_ca <- with_tz(times_utc, "America/Los_Angeles")
target_time <- as.POSIXct("2019-08-01 18:00", tz="America/Los_Angeles")
t_index <- which.min(abs(times_ca - target_time))
r <- rast("wbgt_outputs.nc", subds = "wbgt_new")
# Plot
plot(r[[t_index]])
title(main = paste("WBGT at", format(times_ca[t_index], "%Y-%m-%d %H:%M %Z")), line=3)
```

```{r}
# plot county-level WBGT for Aug 1, 2019 from wbgt_aug_2019_new.nc

# calculate the daily mean for each grid cell and then calculated the county-level mean by overlaying the county shape file

times_utc <- as.POSIXct(ncvar_get(wbgt_outputs, "valid_time"), origin = "1970-01-01", tz = "UTC")
times_ca <- with_tz(times_utc, "America/Los_Angeles")
day_index <- which(as.Date(times_ca) == as.Date("2019-08-01"))


### daily mean for new WBGT
r <- rast("wbgt_outputs.nc", subds = "wbgt_new")

r_day <- mean(r[[day_index]])  # compute daily mean per grid cell

ca_counties <- counties(state = "CA", cb = TRUE, year = 2020) %>%  st_as_sf()
ca_counties <- st_transform(ca_counties, crs(r_day))  # make CRS of ca_counties match CRS of r_day

county_means <- terra::extract(r_day, vect(ca_counties), fun = mean, 
                               weights = TRUE, na.rm = TRUE)

ca_counties$WBGT_mean_new <- county_means[,2]


### daily mean for old WBGT
r <- rast("wbgt_outputs.nc", subds = "wbgt_old")

r_day <- mean(r[[day_index]])  # compute daily mean per grid cell

county_means <- terra::extract(r_day, vect(ca_counties), fun = mean, 
                               weights = TRUE, na.rm = TRUE)

ca_counties$WBGT_mean_old <- county_means[,2]


# plots
ggplot(ca_counties) +
  geom_sf(aes(fill = WBGT_mean_new), color=NA) +
  scale_fill_viridis_c(name = "Daily Mean WBGT (°C)") +
  theme_minimal() +
  labs(title = "New County-Level Daily Mean WBGT", subtitle = "2019-08-01")

ggplot(ca_counties) +
  geom_sf(aes(fill = WBGT_mean_old), color=NA) +
  scale_fill_viridis_c(name = "Daily Mean WBGT (°C)") +
  theme_minimal() +
  labs(title = "Old County-Level Daily Mean WBGT", subtitle = "2019-08-01")
```

```{r}
# plot with same color scale to compare

common_limits <- range(c(ca_map$WBGTmean_C, ca_counties$WBGT_mean_new, ca_counties$WBGT_mean_old))

# from heatvars
ggplot(ca_map) + 
  geom_sf(aes(fill = WBGTmean_C), color = NA) + 
  scale_fill_viridis_c(name = "mean WBGT (C)", limits = common_limits) +
  theme_minimal() + labs(title = "Mean WBGT by County (Spangler)", subtitle = "August 1, 2019")

# from new wbgt calculation
ggplot(ca_counties) +
  geom_sf(aes(fill = WBGT_mean_new), color = NA) +
  scale_fill_viridis_c(name = "Daily Mean WBGT (°C)", limits = common_limits) +
  theme_minimal() +  labs(title = "New County-Level Daily Mean WBGT", subtitle = "2019-08-01")

# from old wbgt calculation
ggplot(ca_counties) +
  geom_sf(aes(fill = WBGT_mean_old), color = NA) +
  scale_fill_viridis_c(name = "Daily Mean WBGT (°C)", limits = common_limits) +
  theme_minimal() +  labs(title = "Old County-Level Daily Mean WBGT", subtitle = "2019-08-01")


# how much they differ (new wbgt compared to Spangler's)
library(dplyr)

comparison <- ca_counties %>%
  st_drop_geometry() %>%
  dplyr::select(GEOID, WBGT_mean_new) %>%
  left_join(
    ca_map %>%
      st_drop_geometry() %>%
      dplyr::select(GEOID, WBGTmean_C),
    by = "GEOID")

comparison <- comparison %>%
  mutate(diff_C = WBGT_mean_new - WBGTmean_C)

summary(comparison$diff_C)

ggplot(comparison, aes(x = WBGTmean_C, y = WBGT_mean_new)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
  geom_smooth(method = "lm", color = "blue") +
  theme_minimal() +
  labs(
    x = "Spangler WBGT",
    y = "New WBGT",
    title = "Comparison of County WBGT Values",
    subtitle = "Red = 1:1 line, Blue = regression")
```


```{r}
####----------Comparing new WBGT with Spangler's

# correlation
ca_map <- st_transform(ca_map, crs(ca_counties))  # make CRS of ca_map match CRS of ca_counties

# comparing WBGT county-level mean for Aug 1, 2019
comparison <- ca_counties |> st_drop_geometry() |>
  dplyr::select(GEOID, calculated_WBGT_mean = WBGT_mean_new) |>
  dplyr::left_join(
    ca_map |>  st_drop_geometry() |>
      dplyr::select(GEOID, heatvars_WBGT_mean = WBGTmean_C), by = "GEOID")

# correlation and RMSE
correlation <- cor(comparison$heatvars_WBGT_mean, comparison$calculated_WBGT_mean)
paste("correlation coefficient: ", correlation)
rmse <- sqrt(mean((comparison$calculated_WBGT_mean - comparison$heatvars_WBGT_mean)^2, na.rm=TRUE))
paste("RMSE: ", rmse)
# bias
bias <- mean(comparison$calculated_WBGT_mean - comparison$heatvars_WBGT_mean, na.rm = TRUE)
paste("bias: ", bias)

# scatterplot
ggplot(comparison, aes(x = heatvars_WBGT_mean, y = calculated_WBGT_mean)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  theme_minimal() +
  labs(x = "heatvars WBGT county-level mean",
    y = "calculated WBGT county-level mean",
    title = "County-Level Comparison for 2019-08-01")



####----------Comparing old WBGT with Spangler's

# correlation
ca_map <- st_transform(ca_map, crs(ca_counties))  # make CRS of ca_map match CRS of ca_counties

# comparing WBGT county-level mean for Aug 1, 2019
comparison <- ca_counties |> st_drop_geometry() |>
  dplyr::select(GEOID, calculated_WBGT_mean = WBGT_mean_old) |>
  dplyr::left_join(
    ca_map |>  st_drop_geometry() |>
      dplyr::select(GEOID, heatvars_WBGT_mean = WBGTmean_C), by = "GEOID")

# correlation and RMSE
correlation <- cor(comparison$heatvars_WBGT_mean, comparison$calculated_WBGT_mean)
paste("correlation coefficient: ", correlation)
rmse <- sqrt(mean((comparison$calculated_WBGT_mean - comparison$heatvars_WBGT_mean)^2, na.rm=TRUE))
paste("RMSE: ", rmse)
# bias
bias <- mean(comparison$calculated_WBGT_mean - comparison$heatvars_WBGT_mean, na.rm = TRUE)
paste("bias: ", bias)

# scatterplot
ggplot(comparison, aes(x = heatvars_WBGT_mean, y = calculated_WBGT_mean)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  theme_minimal() +
  labs(x = "heatvars WBGT county-level mean",
    y = "calculated WBGT county-level mean",
    title = "County-Level Comparison for 2019-08-01")

```










